server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.131.156
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.131.156:3306/changgou_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:   #本地token信息
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:     #本地证书和密钥以及证书密码配置，这里使用非对称加密RSA  公钥加密，私钥解密
  key-store:  #生成证书的时候要设置这些密钥，别名，密码什么的
    location: classpath:/changgou.jks    #证书路径
    secret: changgou   #密钥
    alias: changgou  #证书别名
    password: changgou  #证书密码