server:
  port: 18090
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.131.156:3306/changgou_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.131.156
    port: 6379
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.131.156
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

#enabled: true表示开启Feign的熔断，默认是线程池隔离，每次feign调用的时候开启一个新的线程，线程比较多的时候就会产生熔断
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000
# hystrix配置，信号量隔离
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE

mq:
  pay:
    exchange:
      seckillorder: exchange.order  #接收消息得交换机
    queue:
      seckillorder: queue.order  #队列名称
    routing:
      seckillkey: queue.order
